apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
